baseURL = 'https://heropack-hotline.github.io/HeropackHotlineWebsite/'
languageCode = 'en-US'
title = 'Heropack Hotline'
theme = 'plume'

disableKinds = ['taxonomy', 'term']

[params]
  shortName = 'Heropack Hotline'
  description = 'Heropack Hotline'
  keywords = 'Plume, Hugo, documentation, theme'
  author = 'CandyFreak2'
  backgroundColor = '#ffffff'
  themeColor = '#000000'
  showEditLink = true

  [params.socialLinks]
    discord = 'https://discord.gg/<your-discord-server-invite-link>'
    github = 'https://github.com/Heropack-Hotline/HeropackHotlineWebsite'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Documentation'
    pageRef = '/docs/'
    weight = 20

[outputs]
  home = ['html', 'rss', 'webappmanifest', 'json']

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

  [markup.highlight]
    lineNos = true
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false

      [markup.goldmark.extensions.extras]
        delete.enable = true
        mark.enable = true
        insert.enable = true
        subscript.enable = true
        superscript.enable = true

      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
